### ISSUE TITLE
Will this inject hardcoded values into the options api?

### ISSUE THREAD

**Issue by g000m** [TypistTech/wp-option-store#40]
Can you clarify wether wp-options-store does what I need? I want to create a settings file of keys & values that will be returned the options API when that key is requested.

example:
committed-options.php
$options['key'] = 'value123';

usage in plugin: 
get_option('key') === 'value123';

**Comment by tangrufus** [comment]
Not out-of-the-box.

By default, wp option store first reads from constants. If the value is `null`, read from database.
Finally, apply filters to the value into filters.

See: https://github.com/TypistTech/wp-option-store/blob/566b7e2f6ee455ea1e186e651968d995efcf5f2a/README.md#example

If you want to make use of the built-in strategies (e.g: constants, database, filters), you can implement a custom strategy, see: https://github.com/TypistTech/wp-option-store/blob/566b7e2f6ee455ea1e186e651968d995efcf5f2a/README.md#can-i-implement-my-own-strategy-classes

If you just want to read from a hardcoded file without _failling back_ to other sources or filters, wp option store is not for you. Try something like [`vlucas/phpdotenv`](https://github.com/vlucas/phpdotenv). Bedrock is a good example of using `vlucas/phpdotenv` to [populate configurations](https://github.com/roots/bedrock/blob/e9400200cdbdf00c97e7ad80802c48221ec7ac8d/config/application.php).

Or, if your use case is simple, just use some wordpress `pre_get_option_xxxxxx` filters.
